### PR TITLE
Created Abbreviations.yml

### PR DESCRIPTION
**Pull request by wordsmeanstuff**
https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Abbreviations

### CODE REVIEW

**Comment by wordsmeanstuff** [comment]
Hey Fabri! I'm trying to test this rule on https://studio.vale.sh/ but it says "processing" and doesn't go on. Harumph. 

Would you please take a look? I'm not sure if all of these variations are needed in the example, or if we should use a wildcard... would appreciate your expertise here :)

**Comment by theletterf** [comment]
@wordsmeanstuff Have a look at this other proposal: https://studio.vale.sh/s/0857358f9b28213a9fd121f983a218fd

```
extends: substitution
message: "For keyboard shortcuts, use '%s' instead of '%s'."
link: 'https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Abbreviations'
level: error
ignorecase: false
action:
  name: replace
swap:
  'Ctrl \- alt \- del': Ctrl+Alt+Del
  'Ctrl \+ Alt \+ Del': Ctrl+Alt+Del
  'ctrl \- alt \- del': Ctrl+Alt+Del
  'ctrl \+ alt \+ del': Ctrl+Alt+Del
  '(?:control|ctrl\.|Control|Ctrl\.)(?:\-|\+)': Ctrl+
  '(?:control|ctrl\.|Control|Ctrl\.) \+ ': Ctrl+
 ```

WDYT?

**Comment by wordsmeanstuff** [comment]
I like how you've modified this, Fabri! I have just two questions:

1. If capitalization doesn't matter, is there a difference between these two lines?
  'Ctrl \+ Alt \+ Del': Ctrl+Alt+Del
  'ctrl \+ alt \+ del': Ctrl+Alt+Del
2. I'm wondering if we should modify this a little more. Instead of calling it "Abbreviations" we could call it "Keyboard Shortcuts", and then we could also search for things like Command+C, Shift+Enter, Command+Shift+?, etc. Or is that too cumbersome? I just feel like what this rule is searching for isn't actually abbreviations, but instead the spaces and caps in keyboard strokes. 

As a sidenote, I have it on our editor agenda to review whether "Ctrl" is the most appropriate abbreviation. I am not sure what Windows keyboards say, but my Macbook says "control" and I'm wondering if it's the most OS-agnostic to shorten the word if they keyboard doesn't say that anymore :) Will be back in touch on that.

**Comment by wordsmeanstuff** [comment]
Hey Fabri! I ended up making quitttte a few changes to the guidance for keyboard shortcuts, so I don't think that this rule works, ummm, at all anymore. Our newest guidance says to spell out the name of the keys, but we might still be able to use a rule for catching the spaces between the + signs. And the name "Abbreviations" is probably not the best name for this yaml file anymore ;) 

Thank you for bringing up this rule in the first place so we could take a harder look at our lack of guidance! What's the best way forward? Close this issue and consider whether we want a different one?

New SG topic here: https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Keyboardshortcuts

**Comment by theletterf** [comment]
Let's create a new one! Glad this PR helped expand our guidance anyway! :)

**Pull request closed without merging**
